
project_id = "oflztmlaurxmrgjttjyn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
buckets = [
  { name = "invoices", public = true }
]

[functions.generate-invoice]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.scrape-northdata]
verify_jwt = false

[db]
enabled = true
port = 54322
shadow_port = 54324
major_version = 15

[realtime]
enabled = true
port = 54325
tenant_id = "realtime-dev"

[studio]
enabled = true
port = 54323
