
import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

export const useInvoiceGeneration = () => {
  const [isGenerating, setIsGenerating] = useState(false);
  const { toast } = useToast();

  const generateInvoice = async (orderId: string, shopId?: string, bankAccountId?: string, additionalNotes?: string) => {
    try {
      setIsGenerating(true);
      
      console.log('Generating invoice for order:', orderId, 'with shop:', shopId, 'and bank account:', bankAccountId, 'and additional notes:', additionalNotes);
      
      const { data, error } = await supabase.functions.invoke('generate-invoice', {
        body: { orderId, shopId, bankAccountId, additionalNotes }
      });

      if (error) {
        console.error('Edge function error:', error);
        throw error;
      }

      if (!data || !data.success) {
        console.error('Invoice generation failed:', data?.error);
        throw new Error(data?.error || 'Failed to generate invoice');
      }

      console.log('Invoice generated successfully:', data.invoiceNumber);
      console.log('PDF file URL:', data.fileUrl);
      console.log('Email sent:', data.emailSent);

      // Verify the PDF was properly generated by checking the file
      if (data.fileUrl) {
        try {
          const response = await fetch(data.fileUrl, { method: 'HEAD' });
          if (response.ok) {
            const contentType = response.headers.get('content-type');
            console.log('Generated file content type:', contentType);
            
            if (contentType && !contentType.includes('application/pdf')) {
              console.warn('Generated file may not be a valid PDF:', contentType);
            }
          }
        } catch (fetchError) {
          console.warn('Could not verify PDF file:', fetchError);
        }
      }

      // Show different toast messages based on context - detect if it's Italian
      const isItalian = window.location.hostname === 'gasoliocasa.com';
      
      if (data.emailSent) {
        toast({
          title: isItalian ? 'Successo' : 'Erfolg',
          description: isItalian 
            ? `Fattura ${data.invoiceNumber} è stata generata con successo e inviata via email.`
            : `Rechnung ${data.invoiceNumber} wurde erfolgreich generiert und per E-Mail versendet.`,
        });
      } else {
        toast({
          title: isItalian ? 'Fattura creata' : 'Rechnung erstellt',
          description: isItalian 
            ? `Fattura ${data.invoiceNumber} è stata generata, ma l'email non è stata inviata.`
            : `Rechnung ${data.invoiceNumber} wurde generiert, aber E-Mail konnte nicht versendet werden.`,
          variant: 'default',
        });
      }

      return data;
    } catch (error) {
      console.error('Error generating invoice:', error);
      
      const isItalian = window.location.hostname === 'gasoliocasa.com';
      toast({
        title: isItalian ? 'Errore' : 'Fehler',
        description: isItalian 
          ? 'La fattura non è stata generata. Riprova più tardi.'
          : 'Rechnung konnte nicht generiert werden. Bitte versuchen Sie es erneut.',
        variant: 'destructive',
      });
      throw error;
    } finally {
      setIsGenerating(false);
    }
  };

  return {
    generateInvoice,
    isGenerating
  };
};
