// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oflztmlaurxmrgjttjyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mbHp0bWxhdXJ4bXJnanR0anluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzY5NzcsImV4cCI6MjA2MzkxMjk3N30.acAWF7W-DR5mNJWCXTkI8moqPxynfO12Fg-sI2SOIrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);